language: node_js
node_js:
  - "11"

services:
  - docker

before_install:
  - heroku container:login
  - cd movies

deploy:
  provider: script
  script: heroku container:push web -a hydra-movies; heroku container:release web -a hydra-movies
  on:
    branch: heroku-integration

env:
  global:
    secure: RnC8voz/UmT81NQS6aNPpkGumTTdEnzxX11ulLs9/P+8i2QBpf0n4Bn26fMy6YKSVUfNtolqOamged4s/ljeoNkU/55i6y639wMntoSP/4na8KdATxg9a/Qef2fO75eZXSmJm7/o3Ua0tmoqHWoGa1qefQr6Ygubt8pXUo6rV7qq08TDGA8EXQCxAajNlX8V3Jg+FN9Cljqre1z3XRAkINEHQtdfhkaLDUWqFPSaNezRcl5sl2FSGucg0JrNVBG8i5QCsbQ3lnY7HNC0Sfr8SQFPHy080OlrUvcEOJyT5yLQ2OcSF2S9WRQ4ECGRvYHuqBxbwZ80+XW+egZo2dNKyxBnbyhVuqxRUXd2u1uyPu9J7DIIJnT/IjY7XCjmwLiOk+XE+ielBZ5OfGSu16qWb1jGfopWg8RzVQpvasGrG6IpndFZ/dgysvzppqyRXled6tSnlp67T6vnYiuzymUcso0c9Km7UABQPEI1BMTqMMM5I5wuGoZEOYAXbUyWKZccdNSVHpf/ZW00Racxh47H0jIud91E0GXjf85AgS0bPG2fBpyLxe4XMLQBNh2m8YX2RA4GveHSQYNvWbSrJxCUGlFcsqLwVTAu0kTd8tMHI+s7ndQRelLMlUpA2JjPoY7pxqfdnvTAE4tnUxlMVndk+JgcpeBPkItJQGS0eiRKKfk=
