language: node_js
node_js:
  - "11"

services:
  - docker

before_install:
  - heroku login
  - heroku container:login
  - cd movies

deploy:
  provider: script
  script: heroku container:push web -a hydra-movies; heroku container:release web -a hydra-movies
  on:
    branch: heroku-integration

env:
  global:
    secure: DArbqvA12shEGlc6UCeNOG8qTMhLS+AIoTOWA3ErcUVf+95Cu+8dpLCuyyj0yo8ZFpVLqPn9KuDOg2tAn2pxXSZb0LCi+eOGga4X4zTies+p+uXKyyrRI8h+gG2D5/hBL8VyrIaPUqJcSMMHpToz9jTxG0rrf2EXjVQeBsH5Y1UMHrH5E/acQqm0lWCFEyaL56a1GgRNdXX16Vz9TG2YT+1vbj57Dsrhup983H6Vl80SaEbcUecDOMjDeBzIZIG95Lt6cqseFI4pUBWDokPQl5A/l5ccqKDx0mf2UqxdvQk1s9N2xCXDSrejdZQbfIQ4+V9jSGmSfzTgsRiVhZ5rx90yXymb2YL6yBkh6YBGLQPvnoImuZ1H7ZVs/GhkdfxByC5B6dXVEP//Wjhh5L1vk/NHHiE8xgO3O7Q/gqVROiR1vxD2+Y+p5NULLAuWKL53oycUaTxoaIyoq7bxrUuzOy9XUWbWKHTtp5IcR9p8or2Lr4HERJsSSE+ZMC99R+9oE+iejUT38Set0EGgYQI4WJOViz3docruLOrpNQz6VbcQJbILdd9Mzrfir7gzHwiFvEuvk9W2hPq6geM+aEPSQ2EyGNt5N/jgZF/zkcneXr4HoH7iLkE0+ZvIPip1MiTSN6MDMiV6uRh/ntJrxCdRR51yl1KkL7QNh07DzLTxdzo=
