language: node_js
node_js:
  - "11"

services:
  - docker

before_install:
  - cd movies

deploy:
  provider: script
  script: heroku container:login; heroku container:push web -a hydra-movies; heroku container:release web -a hydra-movies
  on:
    all_branches: true

env:
  global:
    secure: DTqbZQHXn5jj3Ns5uucNbL0RJFrc4AFrVAxuNfOUQIaJdwaMqA2jWLMbT7ANPmlgbvMKbicO5YIckCnsPKBMlm1tf+JTWuvJAhY+P+ld1fIo1/37Tsqi0HTsQmhXKmjQA0dhype14zPis/MP8QawFWuWEMukFB4xAs6S2O9GVtlXHG0IK+L3sbttdfqmqzb0xeaz4lAa3aOLj+O7i2pl2qi8R5F3/E+e2xwpbXTRS3lvY6KfV/kjLWZGGUP9gurMQJ33Jz0S4EFJdjJNvOWs5qbTFxqv9vsa7jItJn6PR0CHIMxAo7pelyAQEuaLKU7u6xHkegkfhD1oOd6MoZHMsIpDGLh7FX1sXQj85GiviT32Lh1z/oy2e4+b7UXyb8GvWH10RwUboJk36KilDBwzwuJmXNs/iH4ST2ZL7v+qH92DiJP0afl7WeUyfvprx8eeoTXlKvTyrprFgMsmh4IL37qX/FA/Hap4DlegboOHF3veko9hPbrUK8V8R8vy8E2gylPOb5RJr8AS4gQ6q2GMD5YpM3s56k4cAodYg6LM60w3jKmUqeBEiDufRZy+IfjmQzhYxoCMpd2uXoke7uyfqyFyhtHr/aYqoXdsVKL8Jgl+R7TR15rZeh8jEnegGYivm8oJ1+LKLq+5FumPaenJCAj+QdCNg/jQZIWUKhsLN7M=
